<x-package.dropdown :name="$name" :id="$id" :value="$value" :label="$label">
    <option value="&#10146;">&#10146; &nbsp; &nbsp; &nbsp;<span>( Three-d top-lighted right arrowhead )</span></option>
    <option value="&#9830;">&#9830; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#8902;">&#8902; &nbsp; &nbsp; &nbsp;<span>( Bold Star )</span></option>
    <option value="&#9733;">&#9733; &nbsp; &nbsp; &nbsp;<span>( Bold Large Star )</span></option>
    <option value="&#9734;">&#9734; &nbsp; &nbsp; &nbsp;<span>( Empty start suit )</span></option>
    <option value="&#10025;">&#10025; &nbsp; &nbsp; &nbsp;<span>( Edgless start suit )</span></option>
    <option value="&#10026;">&#10026; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10027;">&#10027; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10028;">&#10028; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10029;">&#10029; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10030;">&#10030; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10031;">&#10031; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10032;">&#10032; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10033;">&#10033; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10034;">&#10034; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10035;">&#10035; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10036;">&#10036; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10037;">&#10037; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10038;">&#10038; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10039;">&#10039; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10040;">&#10040; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10041;">&#10041; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10042;">&#10042; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10043;">&#10043; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10043;">&#10043; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10044;">&#10044; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10045;">&#10045; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10046;">&#10046; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10047;">&#10047; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10048;">&#10048; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10049;">&#10049; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    <option value="&#10050;">&#10050; &nbsp; &nbsp; &nbsp;<span>( Black diamond suit )</span></option>
    {{-- <option value="&#10162;">&#10162;</option>
    <option value="&#10170;">&#10170;</option>
    <option value="&#10172;"">&#10172;</option> --}}
    <option value="&#8658;">&#8658; &nbsp; &nbsp; &nbsp;<span>( Right double arrow )</span></option>
    <option value="&#9839;">&#9839; &nbsp; &nbsp; &nbsp;<span>( Music sharp sign )</span></option>
    {{-- <option value="&#9850;">&#9850;</option> --}}
    <option value="&#9851;">&#9851; &nbsp; &nbsp; &nbsp;<span>( Black universal recycling symbol )</span></option>
    <option value="&#9856;">&#9856; &nbsp; &nbsp; &nbsp;<span>( Die face )</span></option>
    {{-- <option value="&#9866;">&#9866;</option> --}}
    <option value="&#9872;">&#9872; &nbsp; &nbsp; &nbsp;<span>( White flag )</span></option>
    <option value="&#9873;">&#9873; &nbsp; &nbsp; &nbsp;<span>( Black flag )</span></option>
    <option value="&#9888;">&#9888; &nbsp; &nbsp; &nbsp;<span>( Warning sign )</span></option>
    <option value="&#9896;">&#9896; &nbsp; &nbsp; &nbsp;<span>( Vertical male with stroke sign )</span></option>
    <option value="&#9897;">&#9897; &nbsp; &nbsp; &nbsp;<span>( Horizontal male with stroke sign )</span></option>
    <option value="&#9986;">&#9986; &nbsp; &nbsp; &nbsp;<span>( Black scissors )</span></option>
    <option value="&#9998;">&#9998; &nbsp; &nbsp; &nbsp;<span>( Lower right pencil )</span></option>
    <option value="&#9991;">&#9991; &nbsp; &nbsp; &nbsp;<span>( Tape drive )</span></option>
    <option value="&#10004;">&#10004; &nbsp; &nbsp; &nbsp;<span>( Heavy check mark )</span></option>
    <option value="&#10006;">&#10006; &nbsp; &nbsp; &nbsp;<span>( Heavy multiplication )</span></option>
</x-package.dropdown>